node {
   checkout scm
   def a = load('a.groovy')
   echo("${env.BUILD_NUMBER}")
   echo("${a.LOADED_BUILD_NUMBER}")
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'DockerHubUser') {
        sh "docker build -t zphierzas/jenkins${commit_id} -f ."
       #def app = docker.build("zphierzas/jenkins:${commit_id}", '.').push()
     }
   }
}
